---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: fluentd-ds
  annotations: 
    kubernetes.io/change-cause: "updated to latest"
spec: 
  minReadySeconds: 5
  selector: 
    matchLabels: 
      app: fluentd
  template: 
    metadata: 
      name: fluentd
      labels:
        app: fluentd
    spec: 
      containers: 
        - name: fluentd 
          image: fluentd:latest


    
    