---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector: 
    app: nginx
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pvc
spec: 
  accessModes:  
    - ReadWriteOnce
  hostPath:
    path: "/downloads"
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: gp2  
