---
apiVersion: v1
kind: Pod
metadata: 
  name: restartfailure
spec: 
  restartPolicy: OnFailure
  containers: 
    - name: failure
      image: alpine
      args: 
        - sleep
        - 3s
 ---
 apiVersion: v1
 kind: Pod
 metadata: 
   name: restartfailure2
 spec: 
   restartPolicy: Always
   containers: 
     - name: success
       image: alpine
       args:
         - sleep
         - 3s           
