---
apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spec: 
  backoffLimit: 5
  template:  
    metadata:
      name: jobpod 
    spec: 
      restartpolicy: OnFailure
      containers: 
        - name: alpine
          image: alpine:latest
          command: 
            - sleep 
            - 10s 
          
    


