apiVersion: v1
kind: Service
metadata: 
  name: load-svc
spec: 
  ports: 
    - name: nginx-load
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: nginx
  type: LoadBalancer