apiVersion: batch/v1
kind: CronJob
metada: 
  name: periodicjob
spec: 
  backoffLimit: 2
  schedule: '* * * * *'
  jobTemplate: 
    metadata:
      name: getlivedata
    spec: 
      template:
        metadata:
          name: livedatapod
        spec: 
          restartPolicy: OnFailure
          containers: 
            - name: alpine
              image: alpine
              command:
                - sleep
                - 3s
                 
                   