---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-vol
  labels: 
    app: mysql
    layer: db
spec: 
  containers: 
    - name: mysql
      image: mysql:8
      ports: 
        - containerPort: 3306
      volumeMounts: 
        - name: mysqlpr-volume
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWOR
          value: rootroot 
        - name: MYSQL_USER
          value: abdevops
        - name: MYSQL_PASSWORD
          value: rootroot
          name: MYSQL_DATABASE
          value: employees

  volumes: 
    - name: mysqlpr-volume
      persistentVolumeClaim: 
        claimName: mysql-pvc
        
         