---
apiVersion: v1
kind: Pod
metadata: 
  name: practice
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: 
        - sleep 
        - 1d
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec: 
  selector: 
    app: nginx
  type: ClusterIP
  ports: 
   - name: nginx-svc
     port: 80
     targetPort: 80
     protocol: TCP 
