apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec: 
  selector: 
    app: nginx
    type: clusterIP
    ports: 
      - name: nginx-svc
        port: 80
        targetPort: 80
        protocol: TCP 
    