---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pvc
spec: 
  accessModes:  
    - ReadWriteOnce
  hostPath:
    path: "/downloads"
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: gp2  
