---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: intervaljob
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      name: livedata
    spec:
      template:
        metadata:
          name: livedatapod
        spec: 
          containers: 
            - name: alpine
              image: alpine
              command:
                - sleep
                - 3s


        



