---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: intervaljob
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      name: livedata
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: livedatapod
        spec:
          restartPolicy: OnFailure
          containers: 
            - name: alpine
              image: alpine
              command:
                - sleep
                - 3SM


        



